datacontainer:
  build: DataContainer
cdn:
  build: CDN
  ports:
    - 9090:80
mongo:
  build: Mongo
  volumes_from:
    - datacontainer
  ports:
    - 27017:27017
eventstore:
  build: EventStore
  volumes_from:
    - datacontainer
  ports:
    - 2113:2113
    - 1113:1113
api:
  build: Api
  links:
    - mongo:mongo
    - eventstore:eventstore
    - cdn:cdn