datacontainer:
  build: DataContainer
frontend:
  build: Frontend
  ports:
    - 9090:80
postgres:
  image: postgres
  environment:
    - LANG=en_US.UTF-8
    - POSTGRES_PASSWORD=password
  ports:
    - 5432:5432
eventstore:
  build: EventStore
  ports:
    - 2113:2113
    - 1113:1113
  volumes_from:
    - datacontainer
api:
  build: Api
  links:
    - postgres:postgres
    - eventstore:eventstore
    - frontend:frontend
  ports:
    - 3000:3000
  volumes:
    - Api/app/src:/opt/app/current/src
workflows:
  build: Workflows
  links:
    - postgres:postgres
    - eventstore:eventstore
  volumes:
    - Workflows/app/src:/opt/app/current/src
projections:
  build: Projections
  links:
    - postgres:postgres
    - eventstore:eventstore
  volumes:
    - Projections/app/src:/opt/app/current/src

